#!/usr/bin/env ruby

# Script for loading users and tokens from OpenNebula to user configfile for dyndnsd

require 'opennebula'
require 'yaml'
require 'tempfile'
require 'fileutils'
require 'dyndnsd/opennebula/settings'

include OpenNebula

client = Client.new(Dyndnsd::Opennebula::Settings.credentials, Dyndnsd::Opennebula::Settings.endpoint)

userpool = UserPool.new(client)

rc = userpool.info
if OpenNebula.is_error?(rc)
  puts rc.message
  exit 1
end

users = {}
users['users'] = {}

userpool.each do |user|
  next if Dyndnsd::Opennebula::Settings.exclude.include?(user['ID'].to_i)
  name = user['NAME']
  pass = user['TEMPLATE/TOKEN_PASSWORD']
  domains = Dyndnsd::Opennebula::Settings.domains.map { |domain| "*.#{name}.#{domain}" }
  users['users'][name] = {
    'password' => pass,
    'hosts' => domains
  }
end

begin
  file = Tempfile.new('dyndnsd-users')
  File.open(file, 'w') { |f| f.write(users.to_yaml) }
  FileUtils.cp file.path, Dyndnsd::Opennebula::Settings.outfile
ensure
  if file
    file.close
    file.unlink
  end
end
